parks = [
  { name: 'Acadia National Park', state: 'Maine' },
  { name: 'American Samoa National Park', state: 'American Samoa' },
  { name: 'Arches National Park', state: 'Utah' },
  { name: 'Badlands National Park', state: 'South Dakota' },
  { name: 'Big Bend National Park', state: 'Texas' },
  { name: 'Biscayne National Park', state: 'Florida' },
  { name: 'Black Canyon of the Gunnison National Park', state: 'Colorado' },
  { name: 'Bryce Canyon National Park', state: 'Utah' },
  { name: 'Canyonlands National Park', state: 'Utah' },
  { name: 'Capitol Reef National Park', state: 'Utah' },
  { name: 'Carlsbad Caverns National Park', state: 'New Mexico' },
  { name: 'Channel Islands National Park', state: 'California' },
  { name: 'Congaree National Park', state: 'South Carolina' },
  { name: 'Crater Lake National Park', state: 'Oregon' },
  { name: 'Cuyahoga Valley National Park', state: 'Ohio' },
  { name: 'Death Valley National Park', state: 'California, Nevada' },
  { name: 'Denali National Park and Preserve', state: 'Alaska' },
  { name: 'Dry Tortugas National Park', state: 'Florida' },
  { name: 'Everglades National Park', state: 'Florida' },
  { name: 'Gates of the Arctic National Park and Preserve', state: 'Alaska' },
  { name: 'Glacier Bay National Park and Preserve', state: 'Alaska' },
  { name: 'Glacier National Park', state: 'Montana' },
  { name: 'Grand Canyon National Park', state: 'Arizona' },
  { name: 'Grand Teton National Park', state: 'Wyoming' },
  { name: 'Great Basin National Park', state: 'Nevada' },
  { name: 'Great Sand Dunes National Park and Preserve', state: 'Colorado' },
  { name: 'Great Smoky Mountains National Park NC', state: 'North Carolina' },
  { name: 'Great Smoky Mountains National Park TN', state: 'Tennessee' },
  { name: 'Guadalupe Mountains National Park', state: 'Texas' },
  { name: 'Haleakalā National Park', state: 'Hawaii' },
  { name: 'Hawaii Volcanoes National Park', state: 'Hawaii' },
  { name: 'Hot Springs National Park', state: 'Arkansas' },
  { name: 'Indiana Dunes National Park', state: 'Indiana' },
  { name: 'Isle Royale National Park', state: 'Michigan' },
  { name: 'Joshua Tree National Park', state: 'California' },
  { name: 'Katmai National Park and Preserve', state: 'Alaska' },
  { name: 'Kenai Fjords National Park', state: 'Alaska' },
  { name: 'Kings Canyon National Park', state: 'California' },
  { name: 'Kobuk Valley National Park', state: 'Alaska' },
  { name: 'Lake Clark National Park and Preserve', state: 'Alaska' },
  { name: 'Lassen Volcanic National Park', state: 'California' },
  { name: 'Mammoth Cave National Park', state: 'Kentucky' },
  { name: 'Mesa Verde National Park', state: 'Colorado' },
  { name: 'Mount Rainier National Park', state: 'Washington' },
  { name: 'North Cascades National Park', state: 'Washington' },
  { name: 'Olympic National Park', state: 'Washington' },
  { name: 'Petrified Forest National Park', state: 'Arizona' },
  { name: 'Pinnacles National Park', state: 'California' },
  { name: 'Redwood National and State Parks', state: 'California' },
  { name: 'Rocky Mountain National Park', state: 'Colorado' },
  { name: 'Saguaro National Park', state: 'Arizona' },
  { name: 'Sequoia National Park', state: 'California' },
  { name: 'Shenandoah National Park', state: 'Virginia' },
  { name: 'Theodore Roosevelt National Park', state: 'North Dakota' },

  { name: 'American Samoa', state: 'American Samoa' },
  { name: 'Arches', state: 'Utah' },
  { name: 'Badlands', state: 'South Dakota' },
  { name: 'Big Bend', state: 'Texas' },
  { name: 'Virgin Islands National Park', state: 'U.S. Virgin Islands' },
  { name: 'Voyageurs National Park', state: 'Minnesota' },
  { name: 'Wind Cave National Park', state: 'South Dakota' },
  { name: 'Wrangell–St. Elias National Park and Preserve', state: 'Alaska' },
  { name: 'Yellowstone National Park ID', state: 'Idaho' },
  { name: 'Yellowstone National Park MT', state: 'Montana' },
  { name: 'Yellowstone National Park WY', state: 'Wyoming' },
  { name: 'Yosemite National Park', state: 'California' },
  { name: 'Zion National Park', state: 'Utah' },
]

parks.each do |park|
  Park.create(park)
end
